### PR TITLE
Fix the build on Windows using mingw

### PR DESCRIPTION
**Pull request by philippefoubert**
- static link to mingw libraries (to avoid path issues)
- adjust the path conventions (drive letter) to be able to use existing bash scripts on Windows
- add an install target to be able to build outside the source folder (and keep using existing bash scripts)

### CODE REVIEW

**Review by nhasabni — APPROVED** [review]
Thanks @philippefoubert for the support! It looks great to me.

**Comment by philippefoubert** [comment]
To fix the "[linux/macos]_build_and_test" checks that fail, use [PR#53](https://github.com/IntelLabs/control-flag/pull/53) (since it is not directly related to mingw, i have chosen to write an other PR for that)

**Comment by nhasabni** [comment]
@philippefoubert As a small request, can you please fix the style check errors? You can run cpplint tool on your end like: `cpplint --filter=-build/include_subdir,-runtime/reference --recursive .`

**Review by nhasabni — APPROVED** [review]
This looks great! Thanks again for the change.

**Review by nirhasabnis — APPROVED** [review]

**Pull request merged**
